version: 3.0.0
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'Morpher.WebService.V3.Client\Morpher.WebService.V3.Client.csproj'
  package_version: '{version}'
  assembly_version: '3.0.0'
  file_version: '{version}.{build}'
  informational_version: '{version}.{build}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.csproj --no-build -c Release
artifacts:
- path: '**\*.nupkg'
  name: Nuget