version: 2.0.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: nuget pack Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.nuspec -Version %appveyor_build_version%
artifacts:
- path: '*.nupkg'
  name: Nuget