version: 6.0.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'Morpher.WebService.V3.Client\Morpher.WebService.V3.Client.csproj'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.csproj --no-build -c Release
artifacts:
- path: '**\*.nupkg'
  name: Nuget