environment:
  major_version: 3
  minor_version: 1
  patch_version: 0
version: '$(major_version).$(minor_version).$(patch_version).{build}'
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'Morpher.WebService.V3.Client\Morpher.WebService.V3.Client.csproj'
  package_version: '$(major_version).$(minor_version).$(patch_version)'
  assembly_version: '$(major_version).0.0'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.csproj --no-build -c Release
- cmd: dotnet nuget push -s .\bin\Release\Morpher.WebService.V3.Client.3.1.0.nupkg
artifacts:
- path: '**\*.nupkg'
  name: Nuget